apiVersion: v3.0.2
kind: DataContract
id: awm_poc.awm_instruments
name: Instrument - Master data
version: 0.1.0
status: draft
domain: asset_management
description:
  purpose: Instrument / security master
schema:
- name: awm_instruments
  physicalName: awm_instruments
  logicalType: object
  physicalType: table
  properties:
  - name: instrument_code
    logicalType: string
    physicalType: string
    required: true
    primaryKey: true
    description: CUSIP/ISIN-like code
    quality:
    - type: text
      name: DQ007
      description: 'regex {''pattern'': ''^[A-Z]{2}[A-Z0-9]{9}[0-9]$''}'
  - name: instrument_name
    logicalType: string
    physicalType: string
    required: true
    description: Name
  - name: instrument_type
    logicalType: string
    physicalType: string
    required: true
    description: equity/bond/cash
